Depend on dotty with macros.
To compile

```
sbt
> enableDotty
> testsMacros/compile

s...
[error] -- [E006] Unbound Identifier Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/main.scala:8:30
[error] 8 |  def apply(defn: Any): Any = macro {
[error]   |                              ^^^^^
[error]   |                              not found: macro
[error] -- [E006] Unbound Identifier Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/TestMacros.scala:7:35
[error] 7 |  def structure[T](a: T): String = macro Lit.String(a.structure)
[error]   |                                   ^^^^^
[error]   |                                   not found: macro
[error] -- [E006] Unbound Identifier Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/TestMacros.scala:6:32
[error] 6 |  def syntax[T](a: T): String = macro Lit.String(a.syntax)
[error]   |                                ^^^^^
[error]   |                                not found: macro
[error] -- [E006] Unbound Identifier Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/Serialize.scala:19:37
[error] 19 |  def materialize[T]: Serialize[T] = macro {
[error]    |                                     ^^^^^
[error]    |                                     not found: macro
[error] -- [E006] Unbound Identifier Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/Assert.scala:6:36
[error] 6 |  def assert(cond: Boolean): Unit = macro {
[error]   |                                    ^^^^^
[error]   |                                    not found: macro
[error] -- [E039] Syntax Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/TestMacros.scala:7:45
[error] 7 |  def structure[T](a: T): String = macro Lit.String(a.structure)
[error]   |                                             ^^^^^^
[error]   |                                        ';' expected, but identifier found
[error] -- [E039] Syntax Error: /Users/ollie/dev/macros/tests/macros/src/main/scala/scala/macros/tests/scaladays/TestMacros.scala:6:42
[error] 6 |  def syntax[T](a: T): String = macro Lit.String(a.syntax)
[error]   |                                          ^^^^^^
[error]   |                                        ';' expected, but identifier found
[error] (testsMacros/compile:compileIncremental) Compilation failed
```